//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacultyWebApi
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class course
    {
        public int id { get; set; }
        public string courseNmae { get; set; }
        public string courseDescription { get; set; }
        public Nullable<int> doctor_id { get; set; }
       [JsonIgnore]
       
        public virtual doctor doctor { get; set; }
    }
}
