//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacultyWebApi
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doctor()
        {
            this.courses = new HashSet<course>();
        }
    
        public int id { get; set; }
        public string doctorNmae { get; set; }
        public string doctorTitle { get; set; }
        public string doctorMail { get; set; }
        public byte[] doctorImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<course> courses { get; set; }
    }
}
